name: Test

on: [push, pull_request]

jobs:
  verify_templates_compiled:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: actions/checkout@v2
    - run: gem install bundler
    - run: bundle config set --local without 'development'
    - run: bundle install
    - run: make compile
    - run: git diff --exit-code # Changes to existing files
    - run: test -z "$(git ls-files compiled_starters/ --exclude-standard --others)" # Untracked files

  markdown_lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - run: gem install mdl
    - run: mdl --style relaxed compiled_starters

  uncommenter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle install --verbose
      - run: ruby tests/test_uncommenter.rb

  redis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: "echo ::remove-matcher owner=go::" # Messes with our output
    - run: go get golang.org/x/tools/cmd/goimports
    - run: gem install bundler
    - run: bundle config set --local without 'development'
    - run: bundle install
    - run: make test_redis

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: "echo ::remove-matcher owner=go::" # Messes with our output
    - run: go get golang.org/x/tools/cmd/goimports
    - run: gem install bundler
    - run: bundle config set --local without 'development'
    - run: bundle install
    - run: make test_docker

  git:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: "echo ::remove-matcher owner=go::" # Messes with our output
    - run: go get golang.org/x/tools/cmd/goimports
    - run: gem install bundler
    - run: bundle config set --local without 'development'
    - run: bundle install
    - run: make test_git
